name: Build Python Package

on:
  workflow_dispatch:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
env:
  CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}

permissions:
  contents: read
  actions: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: python-package
    
    steps:
      - name: Install Cloudsmith CLI
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.1
        with:
          oidc-namespace: 'testcheck'
          oidc-service-slug: 'github_action'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade build

      - name: Build package
        run: python3 -m build
          

      - name: Upload artifact
        run: cloudsmith push python testcheck/staging dist/*.tar.gz
