name: Build Python Package

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CLOUDSMITH_NAMESPACE: testcheck  # Ensure this is correct
  CLOUDSMITH_SERVICE_SLUG: github_action  # Ensure this matches your Cloudsmith service account

permissions:
  
  id-token: write  # Required for OIDC authentication

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: python-package
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Cloudsmith CLI
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.1
        with:
          oidc-namespace: ${{ env.CLOUDSMITH_NAMESPACE }}
          oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE_SLUG }}


      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade build

      - name: Build package
        run: python3 -m build
          

      - name: Upload artifact
        run: cloudsmith push python testcheck/staging dist/*.tar.gz
